### ISSUE TITLE
Tips on Changing Default Branch

### ISSUE THREAD

**Issue by mdrhmn** [wid190038/Website-New#1]
Hey, @wid190038! I noticed that you mentioned in your readme in the `master` branches that you weren't quite sure on why the pushed commits were shown in `master` branch instead of `main`. 

The reason why is that on **GitHub**, the default branch set when creating a new repository is `main`. However, if you're pushing commits from IDEs such as **VS Code**, the default branch set is `master`.

To resolve this conflict, you should consider **changing the default branch** in either places. I personally recommend changing the default setting on GitHub. You can refer to the following documentation:

https://docs.github.com/en/github/administering-a-repository/changing-the-default-branch

Hope this helps!

**Comment by wid190038** [comment]
Thanks!!
